/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "F:\\博客\\jiyongchao-qf.github.io\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-2cd85e22",
    path: "/views/Java/2020/Interview.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2cd85e22").then(next)
    },
  },
  {
    name: "v-b10e0c22",
    path: "/views/Java/2020/JVM.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b10e0c22").then(next)
    },
  },
  {
    name: "v-25576ba2",
    path: "/views/Java/2020/JavaForward.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-25576ba2").then(next)
    },
  },
  {
    name: "v-50c9342f",
    path: "/views/Java/2020/Concurrency.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-50c9342f").then(next)
    },
  },
  {
    name: "v-5ea2c74e",
    path: "/views/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5ea2c74e").then(next)
    },
  },
  {
    path: "/views/index.html",
    redirect: "/views/"
  },
  {
    name: "v-34883fbc",
    path: "/views/Spring/SpringBoot.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-34883fbc").then(next)
    },
  },
  {
    name: "v-f7334fcc",
    path: "/views/Spring/SpringCloud.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f7334fcc").then(next)
    },
  },
  {
    name: "v-35b62f2f",
    path: "/views/Java/2020/MyBatis.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-35b62f2f").then(next)
    },
  },
  {
    name: "v-34108d70",
    path: "/views/Spring/SpringFramework.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-34108d70").then(next)
    },
  },
  {
    name: "v-6319eb4e",
    path: "/timeline/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("TimeLines", "v-6319eb4e").then(next)
    },
    meta: {"pid":"timeline","id":"timeline"}
  },
  {
    path: "/timeline/index.html",
    redirect: "/timeline/"
  },
  {
    name: "v-6b31289f",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6b31289f").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-557f834f",
    path: "/views/Java/2020/Functionalprogramming.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-557f834f").then(next)
    },
  },
  {
    name: "v-5cd5c0cf",
    path: "/views/personalInfo/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5cd5c0cf").then(next)
    },
  },
  {
    path: "/views/personalInfo/index.html",
    redirect: "/views/personalInfo/"
  },
  {
    name: "v-3753b0a8",
    path: "/views/images/Functionalprogramming.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3753b0a8").then(next)
    },
  },
  {
    name: "v-b1564aac",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tags", "v-b1564aac").then(next)
    },
    meta: {"pid":"tags","id":"tags"}
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-ef9325c4",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterKey", "v-ef9325c4").then(next)
    },
    meta: {"pid":"categories","id":"categories"}
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    name: "v-93f54166",
    path: "/tag/个人信息/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-93f54166").then(next)
    },
    meta: {"pid":"tags","id":"个人信息"}
  },
  {
    path: "/tag/个人信息/index.html",
    redirect: "/tag/个人信息/"
  },
  {
    path: "/tag/%E4%B8%AA%E4%BA%BA%E4%BF%A1%E6%81%AF/",
    redirect: "/tag/个人信息/"
  },
  {
    name: "v-6137bfcf",
    path: "/categories/Java/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-6137bfcf").then(next)
    },
    meta: {"pid":"categories","id":"Java"}
  },
  {
    path: "/categories/Java/index.html",
    redirect: "/categories/Java/"
  },
  {
    name: "v-3077e678",
    path: "/categories/Spring/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-3077e678").then(next)
    },
    meta: {"pid":"categories","id":"Spring"}
  },
  {
    path: "/categories/Spring/index.html",
    redirect: "/categories/Spring/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]