/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "行则将至.",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "viewport",
        "content": "width=device-width,initial-scale=1,user-scalable=no"
      }
    ]
  ],
  "pages": [
    {
      "title": "面试题精选",
      "frontmatter": {
        "title": "面试题精选",
        "date": "2020-10-07T00:00:00.000Z",
        "categories": [
          "Java"
        ],
        "author": "jyc"
      },
      "regularPath": "/views/Java/2020/Interview.html",
      "relativePath": "views/Java/2020/Interview.md",
      "key": "v-2cd85e22",
      "path": "/views/Java/2020/Interview.html",
      "headers": [
        {
          "level": 2,
          "title": "基础知识",
          "slug": "基础知识"
        },
        {
          "level": 2,
          "title": "集合",
          "slug": "集合"
        },
        {
          "level": 2,
          "title": "常用框架",
          "slug": "常用框架"
        },
        {
          "level": 2,
          "title": "数据库",
          "slug": "数据库"
        }
      ]
    },
    {
      "title": "深入理解JVM",
      "frontmatter": {
        "title": "深入理解JVM",
        "date": "2020-12-6",
        "categories": [
          "Java"
        ],
        "author": "jyc"
      },
      "regularPath": "/views/Java/2020/JVM.html",
      "relativePath": "views/Java/2020/JVM.md",
      "key": "v-b10e0c22",
      "path": "/views/Java/2020/JVM.html"
    },
    {
      "title": "Java基础进阶",
      "frontmatter": {
        "title": "Java基础进阶",
        "date": "2020-12-06T00:00:00.000Z",
        "categories": [
          "Java"
        ],
        "author": "jyc"
      },
      "regularPath": "/views/Java/2020/JavaForward.html",
      "relativePath": "views/Java/2020/JavaForward.md",
      "key": "v-25576ba2",
      "path": "/views/Java/2020/JavaForward.html",
      "headers": [
        {
          "level": 2,
          "title": "代理模式",
          "slug": "代理模式"
        },
        {
          "level": 2,
          "title": "静态代理",
          "slug": "静态代理"
        },
        {
          "level": 2,
          "title": "动态代理",
          "slug": "动态代理-2"
        }
      ]
    },
    {
      "title": "Java并发编程",
      "frontmatter": {
        "title": "Java并发编程",
        "date": "2020-10-05T00:00:00.000Z",
        "categories": [
          "Java"
        ],
        "author": "jyc"
      },
      "regularPath": "/views/Java/2020/Concurrency.html",
      "relativePath": "views/Java/2020/Concurrency.md",
      "key": "v-50c9342f",
      "path": "/views/Java/2020/Concurrency.html",
      "headers": [
        {
          "level": 2,
          "title": "Thread和Runnable",
          "slug": "thread和runnable"
        },
        {
          "level": 2,
          "title": "wait、sleep和notify",
          "slug": "wait、sleep和notify"
        },
        {
          "level": 3,
          "title": "方法简介",
          "slug": "方法简介"
        },
        {
          "level": 3,
          "title": "方法实践",
          "slug": "方法实践"
        },
        {
          "level": 2,
          "title": "synchronized详解",
          "slug": "synchronized详解"
        },
        {
          "level": 3,
          "title": "synchronized简介",
          "slug": "synchronized简介"
        },
        {
          "level": 3,
          "title": "synchronized字节码分析",
          "slug": "synchronized字节码分析"
        },
        {
          "level": 2,
          "title": "Monitor",
          "slug": "monitor"
        },
        {
          "level": 3,
          "title": "自旋",
          "slug": "自旋"
        },
        {
          "level": 3,
          "title": "互斥锁",
          "slug": "互斥锁"
        },
        {
          "level": 3,
          "title": "Monitor源码分析",
          "slug": "monitor源码分析"
        },
        {
          "level": 3,
          "title": "wait、notify源码分析",
          "slug": "wait、notify源码分析"
        },
        {
          "level": 3,
          "title": "锁升级与偏向锁",
          "slug": "锁升级与偏向锁"
        },
        {
          "level": 3,
          "title": "锁粗化与锁消除",
          "slug": "锁粗化与锁消除"
        },
        {
          "level": 2,
          "title": "Lock",
          "slug": "lock"
        },
        {
          "level": 3,
          "title": "死锁及死锁检测",
          "slug": "死锁及死锁检测"
        },
        {
          "level": 3,
          "title": "锁的机制与原理",
          "slug": "锁的机制与原理"
        },
        {
          "level": 3,
          "title": "Condition简介",
          "slug": "condition简介"
        },
        {
          "level": 3,
          "title": "Condition实践",
          "slug": "condition实践"
        }
      ]
    },
    {
      "title": "recoluan's blog website",
      "frontmatter": {},
      "regularPath": "/views/",
      "relativePath": "views/README.md",
      "key": "v-5ea2c74e",
      "path": "/views/",
      "headers": [
        {
          "level": 3,
          "title": "recoluan's blog website",
          "slug": "recoluan-s-blog-website"
        }
      ]
    },
    {
      "title": "SpringBoot",
      "frontmatter": {
        "title": "SpringBoot",
        "date": "2020-07-16T00:00:00.000Z",
        "categories": [
          "Spring"
        ],
        "author": "jyc"
      },
      "regularPath": "/views/Spring/SpringBoot.html",
      "relativePath": "views/Spring/SpringBoot.md",
      "key": "v-34883fbc",
      "path": "/views/Spring/SpringBoot.html"
    },
    {
      "title": "SpringCloud",
      "frontmatter": {
        "title": "SpringCloud",
        "date": "2020-07-16T00:00:00.000Z",
        "categories": [
          "Spring"
        ],
        "author": "jyc"
      },
      "regularPath": "/views/Spring/SpringCloud.html",
      "relativePath": "views/Spring/SpringCloud.md",
      "key": "v-f7334fcc",
      "path": "/views/Spring/SpringCloud.html"
    },
    {
      "title": "MyBatis源码分析",
      "frontmatter": {
        "title": "MyBatis源码分析",
        "date": "2020-7-16",
        "categories": [
          "Java"
        ],
        "author": "jyc"
      },
      "regularPath": "/views/Java/2020/MyBatis.html",
      "relativePath": "views/Java/2020/MyBatis.md",
      "key": "v-35b62f2f",
      "path": "/views/Java/2020/MyBatis.html"
    },
    {
      "title": "SpringFramework",
      "frontmatter": {
        "title": "SpringFramework",
        "date": "2020-07-16T00:00:00.000Z",
        "categories": [
          "Spring"
        ],
        "author": "jyc"
      },
      "regularPath": "/views/Spring/SpringFramework.html",
      "relativePath": "views/Spring/SpringFramework.md",
      "key": "v-34108d70",
      "path": "/views/Spring/SpringFramework.html"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "bgImage": "/banner.jpg",
        "heroText": null,
        "bgImageStyle": {
          "height": "350px"
        },
        "faceImage": "/head.png",
        "heroImage": null,
        "heroImageStyle": {
          "maxHeight": "200px",
          "display": "block",
          "margin": "6rem auto 1.5rem",
          "borderRadius": "50%",
          "boxShadow": "0 5px 18px rgba(0,0,0,0.2)"
        },
        "isShowTitleInHome": false,
        "actionText": "About Me",
        "actionLink": "/views/personalInfo/",
        "features": [
          {
            "title": "Who am I？",
            "details": "A programmer? A human being? Or a matter combination?"
          },
          {
            "title": "Where am I？",
            "details": "In a city? On earth? Or in a small part of space?"
          },
          {
            "title": "What am I gona do？",
            "details": "Work? Struggle? Or go to a destination I don't know?"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-6b31289f",
      "path": "/"
    },
    {
      "title": "函数式编程",
      "frontmatter": {
        "title": "函数式编程",
        "date": "2020-07-13T00:00:00.000Z",
        "categories": [
          "Java"
        ],
        "author": "jyc"
      },
      "regularPath": "/views/Java/2020/Functionalprogramming.html",
      "relativePath": "views/Java/2020/Functionalprogramming.md",
      "key": "v-557f834f",
      "path": "/views/Java/2020/Functionalprogramming.html",
      "headers": [
        {
          "level": 2,
          "title": "函数式编程初识",
          "slug": "函数式编程初识"
        },
        {
          "level": 3,
          "title": "匿名内部类",
          "slug": "匿名内部类"
        },
        {
          "level": 3,
          "title": "Lambda表达式和Stream",
          "slug": "lambda表达式和stream"
        },
        {
          "level": 2,
          "title": "函数式接口",
          "slug": "函数式接口"
        },
        {
          "level": 3,
          "title": "函数式接口定义",
          "slug": "函数式接口定义"
        },
        {
          "level": 3,
          "title": "为什么是函数式接口？",
          "slug": "为什么是函数式接口？"
        },
        {
          "level": 3,
          "title": "Consumer函数式接口",
          "slug": "consumer函数式接口"
        },
        {
          "level": 3,
          "title": "Function函数式接口",
          "slug": "function函数式接口"
        },
        {
          "level": 3,
          "title": "Predicate函数式接口",
          "slug": "predicate函数式接口"
        },
        {
          "level": 3,
          "title": "Supplier函数式接口",
          "slug": "supplier函数式接口"
        },
        {
          "level": 3,
          "title": "函数式接口扩展",
          "slug": "函数式接口扩展"
        },
        {
          "level": 2,
          "title": "方法引用",
          "slug": "方法引用"
        },
        {
          "level": 3,
          "title": "静态方法引用",
          "slug": "静态方法引用"
        },
        {
          "level": 3,
          "title": "实例方法引用",
          "slug": "实例方法引用"
        },
        {
          "level": 3,
          "title": "实例方法名引用",
          "slug": "实例方法名引用"
        },
        {
          "level": 3,
          "title": "构造方法引用",
          "slug": "构造方法引用"
        },
        {
          "level": 3,
          "title": "默认方法",
          "slug": "默认方法"
        },
        {
          "level": 2,
          "title": "Stream实践",
          "slug": "stream实践"
        },
        {
          "level": 3,
          "title": "Stream类源码解析",
          "slug": "stream类源码解析"
        },
        {
          "level": 3,
          "title": "Stream实例剖析",
          "slug": "stream实例剖析"
        },
        {
          "level": 3,
          "title": "Stream陷阱剖析",
          "slug": "stream陷阱剖析"
        },
        {
          "level": 3,
          "title": "内部迭代和外部迭代",
          "slug": "内部迭代和外部迭代"
        },
        {
          "level": 3,
          "title": "流的短路与并发流",
          "slug": "流的短路与并发流"
        },
        {
          "level": 3,
          "title": "分区于分组",
          "slug": "分区于分组"
        },
        {
          "level": 2,
          "title": "Collector接口",
          "slug": "collector接口"
        },
        {
          "level": 3,
          "title": "Comparator源码分析及实践",
          "slug": "comparator源码分析及实践"
        },
        {
          "level": 3,
          "title": "Collector源码分析",
          "slug": "collector源码分析"
        },
        {
          "level": 3,
          "title": "Collector实践",
          "slug": "collector实践"
        },
        {
          "level": 3,
          "title": "自定义Collector",
          "slug": "自定义collector"
        },
        {
          "level": 3,
          "title": "Collectors源码分析",
          "slug": "collectors源码分析"
        },
        {
          "level": 2,
          "title": "Stream原理",
          "slug": "stream原理"
        },
        {
          "level": 3,
          "title": "Stream源码分析",
          "slug": "stream源码分析"
        },
        {
          "level": 3,
          "title": "Spliterator源码分析",
          "slug": "spliterator源码分析"
        },
        {
          "level": 3,
          "title": "Pipeline源码分析",
          "slug": "pipeline源码分析"
        },
        {
          "level": 3,
          "title": "流调用机制与原理",
          "slug": "流调用机制与原理"
        },
        {
          "level": 3,
          "title": "Sink源码分析",
          "slug": "sink源码分析"
        },
        {
          "level": 3,
          "title": "Stream调用流程",
          "slug": "stream调用流程"
        }
      ]
    },
    {
      "title": "个人信息",
      "frontmatter": {
        "title": "个人信息",
        "tags": [
          "个人信息"
        ],
        "date": "2020-07-13T00:00:00.000Z",
        "sidebar": false,
        "isShowComments": false
      },
      "regularPath": "/views/personalInfo/",
      "relativePath": "views/personalInfo/README.md",
      "key": "v-5cd5c0cf",
      "path": "/views/personalInfo/"
    },
    {
      "frontmatter": {},
      "regularPath": "/views/images/Functionalprogramming.html",
      "relativePath": "views/images/Functionalprogramming.md",
      "key": "v-3753b0a8",
      "path": "/views/images/Functionalprogramming.html"
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "个人信息 Tags"
      },
      "regularPath": "/tag/%E4%B8%AA%E4%BA%BA%E4%BF%A1%E6%81%AF/",
      "key": "v-93f54166",
      "path": "/tag/个人信息/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "Java Categories"
      },
      "regularPath": "/categories/Java/",
      "key": "v-6137bfcf",
      "path": "/categories/Java/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "Spring Categories"
      },
      "regularPath": "/categories/Spring/",
      "key": "v-3077e678",
      "path": "/categories/Spring/"
    }
  ],
  "themeConfig": {
    "valineConfig": {
      "appId": "7v2GG0irxq6tRIjc7CqxYSeA-gzGzoHsz",
      "appKey": "DJrwLzOHvrHDmo9x8pGfbIOw"
    },
    "type": "blog",
    "startYear": "2020",
    "author": "吉永超",
    "blogConfig": {
      "category": {
        "location": 2,
        "text": "分类"
      },
      "tag": {
        "location": 3,
        "text": "标签"
      }
    },
    "friendLink": [
      {
        "title": "简书",
        "desc": "不是前端的后端不是好全栈",
        "logo": "jianshu.jpg",
        "link": "https://www.jianshu.com/u/8f5d90376485"
      },
      {
        "title": "掘金",
        "desc": "不是前端的后端不是好全栈",
        "logo": "/juejin.jpg",
        "link": "https://juejin.im/user/1345457965251991"
      }
    ],
    "nav": [
      {
        "text": "首页",
        "link": "/",
        "icon": "reco-home"
      },
      {
        "text": "时间轴",
        "link": "/timeline/",
        "icon": "reco-date"
      },
      {
        "text": "关于我",
        "link": "/views/personalInfo/",
        "icon": "reco-account"
      }
    ],
    "authorAvatar": "/avatar.jpg"
  }
}