/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "个人信息": {
      "key": "个人信息",
      "scope": "tags",
      "path": "/tag/个人信息/",
      "pageKeys": [
        "v-5cd5c0cf"
      ]
    }
  },
  "categories": {
    "Java": {
      "key": "Java",
      "scope": "categories",
      "path": "/categories/Java/",
      "pageKeys": [
        "v-2cd85e22",
        "v-b10e0c22",
        "v-25576ba2",
        "v-50c9342f",
        "v-35b62f2f",
        "v-557f834f"
      ]
    },
    "Spring": {
      "key": "Spring",
      "scope": "categories",
      "path": "/categories/Spring/",
      "pageKeys": [
        "v-34883fbc",
        "v-f7334fcc",
        "v-34108d70"
      ]
    }
  },
  "timeline": {}
}