/**
 * Generated by "@vuepress/plugin-blog"
 */

import sorters from './pageSorters'
import filters from './pageFilters'

export default [{
  pid: "tags",
  id: "个人信息",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/个人信息/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "Java",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/Java/","interval":[0,6]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "Spring",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/Spring/","interval":[0,3]}],
  prevText: "Prev",
  nextText: "Next",
}]