name: CI
on:
  push:
    branches:
      - gh-pages
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 切换分支
        uses: actions/checkout@v2

      - name: 安装依赖
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: 清除Hexo
        uses: heowc/action-hexo@main
        with:
          args: clean

      - name: 生成Hexo
        uses: heowc/action-hexo@main
        with:
          args: generate

      - name: 部署到master分支
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.CI_TOKEN }}
          external_repository: jycoast/jycoast.github.io
          publish_branch: master
          publish_dir: ./public