name: Deployment

on:
  push:
    branches: gh-pages

jobs:
  hexo-deployment:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
    - name: Checkout source
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'

    - name: Install dependencies & Generate static files
      run: |
        node -v
        npm i -g hexo-cli
        npm i
        hexo clean
        hexo g
    - name: Deploy to Github Pages
      env:
        GIT_NAME: jycoast
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        REPO: github.com/jycoast/jycoast.github.io
        GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
        cd ./public && git init && git add .
        git config --global user.name $GIT_NAME
        git config --global user.email $GIT_EMAIL
        git commit -m "Site deployed by GitHub Actions"
        git remote add origin git@github.com:jycoast/jycoast.github.io.git
        git push --force --quiet "https://$GH_TOKEN@github.com/jycoast/jycoast.github.io" master:master