name: Deployment

on:
  push:
    branches: gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Configuration environment
        env:
          HEXO_DEPLOY_PRI: ${{secrets.HEXO_DEPLOY_PRI}}
        run: |
          mkdir -p ~/.ssh/
          echo "-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
NhAAAAAwEAAQAAAYEAwZSmOHwHWMqISVFp0aumZUjMr5R3eePBGhKxpt5KRxFI5wMntLUx
GTFcUNXF/0KvjRZE7CPNzyt6ueJs9JGmkVyxBpTmSA6cU3L6/p2ehbWz+v+xaltv9hdNPM
FdU3dJFMx5xjm3gkGpyO4LDw6FTnWtCrXRlUWjv9Njo6G4Xy5sIGoraWmn1SbmpLkRaQoU
a/pptbrqA+pkWXxo2J65iSFT8siImGwNuwHRu7P+GGZ/zlXzRamg2Fq+EF1Jbp/mGDGiZX
uRIQUSwQcGKQoYsrGhT3tKm/6pKcz4KDzKA90DNBSrS8Z31loyJQRPbJeeqDT5Sjuik2Ku
GBQxo/9Qyxc+mG998PrEXT/31JUXXUfMevHlAx6PEHy6a1pKqrJcHr0AVkBIMj5anfklBG
OG4dCw2th785jbWkVhoJGwRb60rgTiUn08YqLVbRK5P7roaKsrJfuECLep9JO0attMijsi
DS530XFZWNoCTZ235JWhrgd/gEIrwpM1UoyoabtLAAAFgN3ULWnd1C1pAAAAB3NzaC1yc2
EAAAGBAMGUpjh8B1jKiElRadGrpmVIzK+Ud3njwRoSsabeSkcRSOcDJ7S1MRkxXFDVxf9C
r40WROwjzc8rernibPSRppFcsQaU5kgOnFNy+v6dnoW1s/r/sWpbb/YXTTzBXVN3SRTMec
Y5t4JBqcjuCw8OhU51rQq10ZVFo7/TY6OhuF8ubCBqK2lpp9Um5qS5EWkKFGv6abW66gPq
ZFl8aNieuYkhU/LIiJhsDbsB0buz/hhmf85V80WpoNhavhBdSW6f5hgxomV7kSEFEsEHBi
kKGLKxoU97Spv+qSnM+Cg8ygPdAzQUq0vGd9ZaMiUET2yXnqg0+Uo7opNirhgUMaP/UMsX
PphvffD6xF0/99SVF11HzHrx5QMejxB8umtaSqqyXB69AFZASDI+Wp35JQRjhuHQsNrYe/
OY21pFYaCRsEW+tK4E4lJ9PGKi1W0SuT+66GirKyX7hAi3qfSTtGrbTIo7Ig0ud9FxWVja
Ak2dt+SVoa4Hf4BCK8KTNVKMqGm7SwAAAAMBAAEAAAGBAI8UiCeHxQZj7IgEnOpUrRB/1o
qQeh6lsLzMxHJKKyyMIg5dzqNKqZetXEaDO22IpKjrpNXFQQG3aWarbUz3ut4GXPI4bF0m
L3WertYzOlAqFXWYOFIcc4y5fGVDpu9iY6nz2K4jSvgEALJ6/8GJQg7T+6rG6LokVvwaCr
OPfO8dKN5smtm3Nk3eCuwFvlCdGqsU0713AjEStklOI1C5QPmSoLH6drvyYdOvbI4IY+81
E5I3BTCgSDqiF4mQ6g3SML7Co8Yh08/MXnBkLES0ePSQ5ES6fp8uU1ZW+d6K+MXotYGFrM
E4BWv3pizMjiFJ43qIP4jEF6bFUFe4aPrm4Mii6PuKxzcWsjMTC7gLFLmU3uRg7ewFsDH5
RCyHtsWsfHvFxT5brg68THP+X+YmyFmqgdRFNEAArijh6mjVeB5hBmgsVSOE9H0n17Kmzq
oqmtby4sOsEr7VK8wTkKcyLWTNgjeDAE2Au1HE5HBW1cMtfXAII2x+j7Yj9P1bSuu+AQAA
AMAIywdi6tSfXZzgayEWXUL2yDaSluWA9CT0wkSZYfzS2stK8df+hriAMOzfs8kmVA8oI0
EP3ls/xCeiVAmC5G1jwd5RxVy8v33wAECkAq6BQkksjtrprLPdJF3rLFl0Z5zfpzmyT1gz
9smJj7dwmTYRKVDADAD+lFiuCzrwVSDJVz2xMenGKBz1YVw5jdPIH8U3nTbRl+k5bIEb91
P6AxhhvXZyolcfzzKg6u6uRDf3qNA8Sjw/mcrhOZSeC23VwloAAADBAOWy57BId1eMTh5C
Q5TtgaEgyahWxQC5TFvpzqv7ugL5NNOPqA85YstbNd1UOVju32IouYrofjQV+fV0zB+Hgg
nAYxRvcmeIvaHnijMz0K4VNMmQWewHNJXGI4oT5mk3b0Eeo3I8VtMvp+GoZvarg59P54xQ
UPM65DTU1Al9QpG+m5gvbZSrGBaathBeap0eQvJOkI6e73YbCfwk9suB+6DNiBTVK3S28d
M9G5IXfhJUovKe1tgZI2r6LWBmC34oawAAAMEA178Fv8g1eKIViGo3Q6aPKCzj4lcHGTyO
HostmXxXaIIUwoxLM5AMhhYEKae95NspM6MBYVyGnSCyHxwIGvt80iWYAQq6I8ZzbAtcHE
qsgpWxOQ49xx9SZ+QtESgaMlO4m3tvWEcvgkNyFtzADx74ZETbvzX5geJZ3BXDL38iznYI
ClyYIUARQp90wLPK+RDjLn/QNXMJ92fYvqPx8wvryRyOvVeGBzv8SfS5d1pkeGTCiiqd+m
H112NcwDe8CvChAAAAB0hFWE8gQ0QBAgM=
-----END OPENSSH PRIVATE KEY-----
" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name "jycoast"
          git config --global user.email "jiyongchao.19961"
      - name: Install dependencies
        run: |
          npm i -g hexo-cli
          npm i
      - name: Deploy hexo
        run: |
          hexo clean && hexo generate && hexo deploy